### ISSUE TITLE
Joins HOH but does not move

### ISSUE THREAD

**Issue by DrinkingGam** [Jukkales/HoardFarm#6]
Hello sorry for disturbing you. When i am using it it seems she joins and does and use the pomander just fine but she does not walk , and goes striaght to chest . Is there anything i am doing wrong or did set up wrong?

**Comment by Jukkales** [comment]
did you installed vnavmesh correctly? you might can send me a `/xllog` when its not moving

**Comment by DrinkingGam** [comment]
How do i send a Xllog? and i just instaled like enable the plugin.

**Comment by DrinkingGam** [comment]
Actually nevermind its working now. It seems other Plugins was having a conflict. Sorry for disturbing
